package com.gx.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ObjEntProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public ObjEntProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Long value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Long value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Long value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Long value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Long value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Long value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Long> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Long> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Long value1, Long value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Long value1, Long value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andM_priceIsNull() {
            addCriterion("m_price is null");
            return (Criteria) this;
        }

        public Criteria andM_priceIsNotNull() {
            addCriterion("m_price is not null");
            return (Criteria) this;
        }

        public Criteria andM_priceEqualTo(BigDecimal value) {
            addCriterion("m_price =", value, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceNotEqualTo(BigDecimal value) {
            addCriterion("m_price <>", value, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceGreaterThan(BigDecimal value) {
            addCriterion("m_price >", value, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("m_price >=", value, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceLessThan(BigDecimal value) {
            addCriterion("m_price <", value, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("m_price <=", value, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceIn(List<BigDecimal> values) {
            addCriterion("m_price in", values, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceNotIn(List<BigDecimal> values) {
            addCriterion("m_price not in", values, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("m_price between", value1, value2, "m_price");
            return (Criteria) this;
        }

        public Criteria andM_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("m_price not between", value1, value2, "m_price");
            return (Criteria) this;
        }

        public Criteria andO_priceIsNull() {
            addCriterion("o_price is null");
            return (Criteria) this;
        }

        public Criteria andO_priceIsNotNull() {
            addCriterion("o_price is not null");
            return (Criteria) this;
        }

        public Criteria andO_priceEqualTo(BigDecimal value) {
            addCriterion("o_price =", value, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceNotEqualTo(BigDecimal value) {
            addCriterion("o_price <>", value, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceGreaterThan(BigDecimal value) {
            addCriterion("o_price >", value, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("o_price >=", value, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceLessThan(BigDecimal value) {
            addCriterion("o_price <", value, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("o_price <=", value, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceIn(List<BigDecimal> values) {
            addCriterion("o_price in", values, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceNotIn(List<BigDecimal> values) {
            addCriterion("o_price not in", values, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_price between", value1, value2, "o_price");
            return (Criteria) this;
        }

        public Criteria andO_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("o_price not between", value1, value2, "o_price");
            return (Criteria) this;
        }

        public Criteria andShip_addressIsNull() {
            addCriterion("ship_address is null");
            return (Criteria) this;
        }

        public Criteria andShip_addressIsNotNull() {
            addCriterion("ship_address is not null");
            return (Criteria) this;
        }

        public Criteria andShip_addressEqualTo(Integer value) {
            addCriterion("ship_address =", value, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressNotEqualTo(Integer value) {
            addCriterion("ship_address <>", value, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressGreaterThan(Integer value) {
            addCriterion("ship_address >", value, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressGreaterThanOrEqualTo(Integer value) {
            addCriterion("ship_address >=", value, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressLessThan(Integer value) {
            addCriterion("ship_address <", value, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressLessThanOrEqualTo(Integer value) {
            addCriterion("ship_address <=", value, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressIn(List<Integer> values) {
            addCriterion("ship_address in", values, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressNotIn(List<Integer> values) {
            addCriterion("ship_address not in", values, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressBetween(Integer value1, Integer value2) {
            addCriterion("ship_address between", value1, value2, "ship_address");
            return (Criteria) this;
        }

        public Criteria andShip_addressNotBetween(Integer value1, Integer value2) {
            addCriterion("ship_address not between", value1, value2, "ship_address");
            return (Criteria) this;
        }

        public Criteria andMin_orderIsNull() {
            addCriterion("min_order is null");
            return (Criteria) this;
        }

        public Criteria andMin_orderIsNotNull() {
            addCriterion("min_order is not null");
            return (Criteria) this;
        }

        public Criteria andMin_orderEqualTo(Integer value) {
            addCriterion("min_order =", value, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderNotEqualTo(Integer value) {
            addCriterion("min_order <>", value, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderGreaterThan(Integer value) {
            addCriterion("min_order >", value, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_order >=", value, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderLessThan(Integer value) {
            addCriterion("min_order <", value, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderLessThanOrEqualTo(Integer value) {
            addCriterion("min_order <=", value, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderIn(List<Integer> values) {
            addCriterion("min_order in", values, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderNotIn(List<Integer> values) {
            addCriterion("min_order not in", values, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderBetween(Integer value1, Integer value2) {
            addCriterion("min_order between", value1, value2, "min_order");
            return (Criteria) this;
        }

        public Criteria andMin_orderNotBetween(Integer value1, Integer value2) {
            addCriterion("min_order not between", value1, value2, "min_order");
            return (Criteria) this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("brand is null");
            return (Criteria) this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("brand is not null");
            return (Criteria) this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("brand =", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("brand <>", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("brand >", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("brand >=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("brand <", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("brand <=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("brand like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("brand not like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandIn(List<String> values) {
            addCriterion("brand in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotIn(List<String> values) {
            addCriterion("brand not in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("brand between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("brand not between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andP_typeIsNull() {
            addCriterion("p_type is null");
            return (Criteria) this;
        }

        public Criteria andP_typeIsNotNull() {
            addCriterion("p_type is not null");
            return (Criteria) this;
        }

        public Criteria andP_typeEqualTo(String value) {
            addCriterion("p_type =", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeNotEqualTo(String value) {
            addCriterion("p_type <>", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeGreaterThan(String value) {
            addCriterion("p_type >", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeGreaterThanOrEqualTo(String value) {
            addCriterion("p_type >=", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeLessThan(String value) {
            addCriterion("p_type <", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeLessThanOrEqualTo(String value) {
            addCriterion("p_type <=", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeLike(String value) {
            addCriterion("p_type like", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeNotLike(String value) {
            addCriterion("p_type not like", value, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeIn(List<String> values) {
            addCriterion("p_type in", values, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeNotIn(List<String> values) {
            addCriterion("p_type not in", values, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeBetween(String value1, String value2) {
            addCriterion("p_type between", value1, value2, "p_type");
            return (Criteria) this;
        }

        public Criteria andP_typeNotBetween(String value1, String value2) {
            addCriterion("p_type not between", value1, value2, "p_type");
            return (Criteria) this;
        }

        public Criteria andAfter_saleIsNull() {
            addCriterion("after_sale is null");
            return (Criteria) this;
        }

        public Criteria andAfter_saleIsNotNull() {
            addCriterion("after_sale is not null");
            return (Criteria) this;
        }

        public Criteria andAfter_saleEqualTo(String value) {
            addCriterion("after_sale =", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleNotEqualTo(String value) {
            addCriterion("after_sale <>", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleGreaterThan(String value) {
            addCriterion("after_sale >", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleGreaterThanOrEqualTo(String value) {
            addCriterion("after_sale >=", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleLessThan(String value) {
            addCriterion("after_sale <", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleLessThanOrEqualTo(String value) {
            addCriterion("after_sale <=", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleLike(String value) {
            addCriterion("after_sale like", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleNotLike(String value) {
            addCriterion("after_sale not like", value, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleIn(List<String> values) {
            addCriterion("after_sale in", values, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleNotIn(List<String> values) {
            addCriterion("after_sale not in", values, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleBetween(String value1, String value2) {
            addCriterion("after_sale between", value1, value2, "after_sale");
            return (Criteria) this;
        }

        public Criteria andAfter_saleNotBetween(String value1, String value2) {
            addCriterion("after_sale not between", value1, value2, "after_sale");
            return (Criteria) this;
        }

        public Criteria andInvoiceIsNull() {
            addCriterion("invoice is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIsNotNull() {
            addCriterion("invoice is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceEqualTo(String value) {
            addCriterion("invoice =", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceNotEqualTo(String value) {
            addCriterion("invoice <>", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceGreaterThan(String value) {
            addCriterion("invoice >", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceGreaterThanOrEqualTo(String value) {
            addCriterion("invoice >=", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceLessThan(String value) {
            addCriterion("invoice <", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceLessThanOrEqualTo(String value) {
            addCriterion("invoice <=", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceLike(String value) {
            addCriterion("invoice like", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceNotLike(String value) {
            addCriterion("invoice not like", value, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceIn(List<String> values) {
            addCriterion("invoice in", values, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceNotIn(List<String> values) {
            addCriterion("invoice not in", values, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceBetween(String value1, String value2) {
            addCriterion("invoice between", value1, value2, "invoice");
            return (Criteria) this;
        }

        public Criteria andInvoiceNotBetween(String value1, String value2) {
            addCriterion("invoice not between", value1, value2, "invoice");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(String value) {
            addCriterion("stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(String value) {
            addCriterion("stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(String value) {
            addCriterion("stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(String value) {
            addCriterion("stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(String value) {
            addCriterion("stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(String value) {
            addCriterion("stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLike(String value) {
            addCriterion("stock like", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotLike(String value) {
            addCriterion("stock not like", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<String> values) {
            addCriterion("stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<String> values) {
            addCriterion("stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(String value1, String value2) {
            addCriterion("stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(String value1, String value2) {
            addCriterion("stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStock_numIsNull() {
            addCriterion("stock_num is null");
            return (Criteria) this;
        }

        public Criteria andStock_numIsNotNull() {
            addCriterion("stock_num is not null");
            return (Criteria) this;
        }

        public Criteria andStock_numEqualTo(Integer value) {
            addCriterion("stock_num =", value, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numNotEqualTo(Integer value) {
            addCriterion("stock_num <>", value, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numGreaterThan(Integer value) {
            addCriterion("stock_num >", value, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_num >=", value, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numLessThan(Integer value) {
            addCriterion("stock_num <", value, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numLessThanOrEqualTo(Integer value) {
            addCriterion("stock_num <=", value, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numIn(List<Integer> values) {
            addCriterion("stock_num in", values, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numNotIn(List<Integer> values) {
            addCriterion("stock_num not in", values, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numBetween(Integer value1, Integer value2) {
            addCriterion("stock_num between", value1, value2, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_numNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_num not between", value1, value2, "stock_num");
            return (Criteria) this;
        }

        public Criteria andStock_priceIsNull() {
            addCriterion("stock_price is null");
            return (Criteria) this;
        }

        public Criteria andStock_priceIsNotNull() {
            addCriterion("stock_price is not null");
            return (Criteria) this;
        }

        public Criteria andStock_priceEqualTo(BigDecimal value) {
            addCriterion("stock_price =", value, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceNotEqualTo(BigDecimal value) {
            addCriterion("stock_price <>", value, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceGreaterThan(BigDecimal value) {
            addCriterion("stock_price >", value, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stock_price >=", value, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceLessThan(BigDecimal value) {
            addCriterion("stock_price <", value, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stock_price <=", value, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceIn(List<BigDecimal> values) {
            addCriterion("stock_price in", values, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceNotIn(List<BigDecimal> values) {
            addCriterion("stock_price not in", values, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stock_price between", value1, value2, "stock_price");
            return (Criteria) this;
        }

        public Criteria andStock_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stock_price not between", value1, value2, "stock_price");
            return (Criteria) this;
        }

        public Criteria andLower_warnIsNull() {
            addCriterion("lower_warn is null");
            return (Criteria) this;
        }

        public Criteria andLower_warnIsNotNull() {
            addCriterion("lower_warn is not null");
            return (Criteria) this;
        }

        public Criteria andLower_warnEqualTo(Integer value) {
            addCriterion("lower_warn =", value, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnNotEqualTo(Integer value) {
            addCriterion("lower_warn <>", value, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnGreaterThan(Integer value) {
            addCriterion("lower_warn >", value, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnGreaterThanOrEqualTo(Integer value) {
            addCriterion("lower_warn >=", value, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnLessThan(Integer value) {
            addCriterion("lower_warn <", value, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnLessThanOrEqualTo(Integer value) {
            addCriterion("lower_warn <=", value, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnIn(List<Integer> values) {
            addCriterion("lower_warn in", values, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnNotIn(List<Integer> values) {
            addCriterion("lower_warn not in", values, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnBetween(Integer value1, Integer value2) {
            addCriterion("lower_warn between", value1, value2, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andLower_warnNotBetween(Integer value1, Integer value2) {
            addCriterion("lower_warn not between", value1, value2, "lower_warn");
            return (Criteria) this;
        }

        public Criteria andImg_0IsNull() {
            addCriterion("img_0 is null");
            return (Criteria) this;
        }

        public Criteria andImg_0IsNotNull() {
            addCriterion("img_0 is not null");
            return (Criteria) this;
        }

        public Criteria andImg_0EqualTo(String value) {
            addCriterion("img_0 =", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0NotEqualTo(String value) {
            addCriterion("img_0 <>", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0GreaterThan(String value) {
            addCriterion("img_0 >", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0GreaterThanOrEqualTo(String value) {
            addCriterion("img_0 >=", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0LessThan(String value) {
            addCriterion("img_0 <", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0LessThanOrEqualTo(String value) {
            addCriterion("img_0 <=", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0Like(String value) {
            addCriterion("img_0 like", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0NotLike(String value) {
            addCriterion("img_0 not like", value, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0In(List<String> values) {
            addCriterion("img_0 in", values, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0NotIn(List<String> values) {
            addCriterion("img_0 not in", values, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0Between(String value1, String value2) {
            addCriterion("img_0 between", value1, value2, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_0NotBetween(String value1, String value2) {
            addCriterion("img_0 not between", value1, value2, "img_0");
            return (Criteria) this;
        }

        public Criteria andImg_1IsNull() {
            addCriterion("img_1 is null");
            return (Criteria) this;
        }

        public Criteria andImg_1IsNotNull() {
            addCriterion("img_1 is not null");
            return (Criteria) this;
        }

        public Criteria andImg_1EqualTo(String value) {
            addCriterion("img_1 =", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1NotEqualTo(String value) {
            addCriterion("img_1 <>", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1GreaterThan(String value) {
            addCriterion("img_1 >", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1GreaterThanOrEqualTo(String value) {
            addCriterion("img_1 >=", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1LessThan(String value) {
            addCriterion("img_1 <", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1LessThanOrEqualTo(String value) {
            addCriterion("img_1 <=", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1Like(String value) {
            addCriterion("img_1 like", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1NotLike(String value) {
            addCriterion("img_1 not like", value, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1In(List<String> values) {
            addCriterion("img_1 in", values, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1NotIn(List<String> values) {
            addCriterion("img_1 not in", values, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1Between(String value1, String value2) {
            addCriterion("img_1 between", value1, value2, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_1NotBetween(String value1, String value2) {
            addCriterion("img_1 not between", value1, value2, "img_1");
            return (Criteria) this;
        }

        public Criteria andImg_2IsNull() {
            addCriterion("img_2 is null");
            return (Criteria) this;
        }

        public Criteria andImg_2IsNotNull() {
            addCriterion("img_2 is not null");
            return (Criteria) this;
        }

        public Criteria andImg_2EqualTo(String value) {
            addCriterion("img_2 =", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2NotEqualTo(String value) {
            addCriterion("img_2 <>", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2GreaterThan(String value) {
            addCriterion("img_2 >", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2GreaterThanOrEqualTo(String value) {
            addCriterion("img_2 >=", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2LessThan(String value) {
            addCriterion("img_2 <", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2LessThanOrEqualTo(String value) {
            addCriterion("img_2 <=", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2Like(String value) {
            addCriterion("img_2 like", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2NotLike(String value) {
            addCriterion("img_2 not like", value, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2In(List<String> values) {
            addCriterion("img_2 in", values, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2NotIn(List<String> values) {
            addCriterion("img_2 not in", values, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2Between(String value1, String value2) {
            addCriterion("img_2 between", value1, value2, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_2NotBetween(String value1, String value2) {
            addCriterion("img_2 not between", value1, value2, "img_2");
            return (Criteria) this;
        }

        public Criteria andImg_3IsNull() {
            addCriterion("img_3 is null");
            return (Criteria) this;
        }

        public Criteria andImg_3IsNotNull() {
            addCriterion("img_3 is not null");
            return (Criteria) this;
        }

        public Criteria andImg_3EqualTo(String value) {
            addCriterion("img_3 =", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3NotEqualTo(String value) {
            addCriterion("img_3 <>", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3GreaterThan(String value) {
            addCriterion("img_3 >", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3GreaterThanOrEqualTo(String value) {
            addCriterion("img_3 >=", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3LessThan(String value) {
            addCriterion("img_3 <", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3LessThanOrEqualTo(String value) {
            addCriterion("img_3 <=", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3Like(String value) {
            addCriterion("img_3 like", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3NotLike(String value) {
            addCriterion("img_3 not like", value, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3In(List<String> values) {
            addCriterion("img_3 in", values, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3NotIn(List<String> values) {
            addCriterion("img_3 not in", values, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3Between(String value1, String value2) {
            addCriterion("img_3 between", value1, value2, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_3NotBetween(String value1, String value2) {
            addCriterion("img_3 not between", value1, value2, "img_3");
            return (Criteria) this;
        }

        public Criteria andImg_4IsNull() {
            addCriterion("img_4 is null");
            return (Criteria) this;
        }

        public Criteria andImg_4IsNotNull() {
            addCriterion("img_4 is not null");
            return (Criteria) this;
        }

        public Criteria andImg_4EqualTo(String value) {
            addCriterion("img_4 =", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4NotEqualTo(String value) {
            addCriterion("img_4 <>", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4GreaterThan(String value) {
            addCriterion("img_4 >", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4GreaterThanOrEqualTo(String value) {
            addCriterion("img_4 >=", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4LessThan(String value) {
            addCriterion("img_4 <", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4LessThanOrEqualTo(String value) {
            addCriterion("img_4 <=", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4Like(String value) {
            addCriterion("img_4 like", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4NotLike(String value) {
            addCriterion("img_4 not like", value, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4In(List<String> values) {
            addCriterion("img_4 in", values, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4NotIn(List<String> values) {
            addCriterion("img_4 not in", values, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4Between(String value1, String value2) {
            addCriterion("img_4 between", value1, value2, "img_4");
            return (Criteria) this;
        }

        public Criteria andImg_4NotBetween(String value1, String value2) {
            addCriterion("img_4 not between", value1, value2, "img_4");
            return (Criteria) this;
        }

        public Criteria andDetailIsNull() {
            addCriterion("detail is null");
            return (Criteria) this;
        }

        public Criteria andDetailIsNotNull() {
            addCriterion("detail is not null");
            return (Criteria) this;
        }

        public Criteria andDetailEqualTo(String value) {
            addCriterion("detail =", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotEqualTo(String value) {
            addCriterion("detail <>", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThan(String value) {
            addCriterion("detail >", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailGreaterThanOrEqualTo(String value) {
            addCriterion("detail >=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThan(String value) {
            addCriterion("detail <", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLessThanOrEqualTo(String value) {
            addCriterion("detail <=", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailLike(String value) {
            addCriterion("detail like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotLike(String value) {
            addCriterion("detail not like", value, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailIn(List<String> values) {
            addCriterion("detail in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotIn(List<String> values) {
            addCriterion("detail not in", values, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailBetween(String value1, String value2) {
            addCriterion("detail between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andDetailNotBetween(String value1, String value2) {
            addCriterion("detail not between", value1, value2, "detail");
            return (Criteria) this;
        }

        public Criteria andStock_updateIsNull() {
            addCriterion("stock_update is null");
            return (Criteria) this;
        }

        public Criteria andStock_updateIsNotNull() {
            addCriterion("stock_update is not null");
            return (Criteria) this;
        }

        public Criteria andStock_updateEqualTo(String value) {
            addCriterion("stock_update =", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateNotEqualTo(String value) {
            addCriterion("stock_update <>", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateGreaterThan(String value) {
            addCriterion("stock_update >", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateGreaterThanOrEqualTo(String value) {
            addCriterion("stock_update >=", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateLessThan(String value) {
            addCriterion("stock_update <", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateLessThanOrEqualTo(String value) {
            addCriterion("stock_update <=", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateLike(String value) {
            addCriterion("stock_update like", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateNotLike(String value) {
            addCriterion("stock_update not like", value, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateIn(List<String> values) {
            addCriterion("stock_update in", values, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateNotIn(List<String> values) {
            addCriterion("stock_update not in", values, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateBetween(String value1, String value2) {
            addCriterion("stock_update between", value1, value2, "stock_update");
            return (Criteria) this;
        }

        public Criteria andStock_updateNotBetween(String value1, String value2) {
            addCriterion("stock_update not between", value1, value2, "stock_update");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("period is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("period is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(String value) {
            addCriterion("period =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(String value) {
            addCriterion("period <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(String value) {
            addCriterion("period >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(String value) {
            addCriterion("period >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(String value) {
            addCriterion("period <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(String value) {
            addCriterion("period <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLike(String value) {
            addCriterion("period like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotLike(String value) {
            addCriterion("period not like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<String> values) {
            addCriterion("period in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<String> values) {
            addCriterion("period not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(String value1, String value2) {
            addCriterion("period between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(String value1, String value2) {
            addCriterion("period not between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPublishIsNull() {
            addCriterion("publish is null");
            return (Criteria) this;
        }

        public Criteria andPublishIsNotNull() {
            addCriterion("publish is not null");
            return (Criteria) this;
        }

        public Criteria andPublishEqualTo(String value) {
            addCriterion("publish =", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishNotEqualTo(String value) {
            addCriterion("publish <>", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishGreaterThan(String value) {
            addCriterion("publish >", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishGreaterThanOrEqualTo(String value) {
            addCriterion("publish >=", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishLessThan(String value) {
            addCriterion("publish <", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishLessThanOrEqualTo(String value) {
            addCriterion("publish <=", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishLike(String value) {
            addCriterion("publish like", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishNotLike(String value) {
            addCriterion("publish not like", value, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishIn(List<String> values) {
            addCriterion("publish in", values, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishNotIn(List<String> values) {
            addCriterion("publish not in", values, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishBetween(String value1, String value2) {
            addCriterion("publish between", value1, value2, "publish");
            return (Criteria) this;
        }

        public Criteria andPublishNotBetween(String value1, String value2) {
            addCriterion("publish not between", value1, value2, "publish");
            return (Criteria) this;
        }

        public Criteria andPublish_tmIsNull() {
            addCriterion("publish_tm is null");
            return (Criteria) this;
        }

        public Criteria andPublish_tmIsNotNull() {
            addCriterion("publish_tm is not null");
            return (Criteria) this;
        }

        public Criteria andPublish_tmEqualTo(Date value) {
            addCriterion("publish_tm =", value, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmNotEqualTo(Date value) {
            addCriterion("publish_tm <>", value, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmGreaterThan(Date value) {
            addCriterion("publish_tm >", value, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_tm >=", value, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmLessThan(Date value) {
            addCriterion("publish_tm <", value, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmLessThanOrEqualTo(Date value) {
            addCriterion("publish_tm <=", value, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmIn(List<Date> values) {
            addCriterion("publish_tm in", values, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmNotIn(List<Date> values) {
            addCriterion("publish_tm not in", values, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmBetween(Date value1, Date value2) {
            addCriterion("publish_tm between", value1, value2, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andPublish_tmNotBetween(Date value1, Date value2) {
            addCriterion("publish_tm not between", value1, value2, "publish_tm");
            return (Criteria) this;
        }

        public Criteria andSale_numIsNull() {
            addCriterion("sale_num is null");
            return (Criteria) this;
        }

        public Criteria andSale_numIsNotNull() {
            addCriterion("sale_num is not null");
            return (Criteria) this;
        }

        public Criteria andSale_numEqualTo(Integer value) {
            addCriterion("sale_num =", value, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numNotEqualTo(Integer value) {
            addCriterion("sale_num <>", value, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numGreaterThan(Integer value) {
            addCriterion("sale_num >", value, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_num >=", value, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numLessThan(Integer value) {
            addCriterion("sale_num <", value, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numLessThanOrEqualTo(Integer value) {
            addCriterion("sale_num <=", value, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numIn(List<Integer> values) {
            addCriterion("sale_num in", values, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numNotIn(List<Integer> values) {
            addCriterion("sale_num not in", values, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numBetween(Integer value1, Integer value2) {
            addCriterion("sale_num between", value1, value2, "sale_num");
            return (Criteria) this;
        }

        public Criteria andSale_numNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_num not between", value1, value2, "sale_num");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIs_deleteEqualTo(String value) {
            addCriterion("is_delete =", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotEqualTo(String value) {
            addCriterion("is_delete <>", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteGreaterThan(String value) {
            addCriterion("is_delete >", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteGreaterThanOrEqualTo(String value) {
            addCriterion("is_delete >=", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLessThan(String value) {
            addCriterion("is_delete <", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLessThanOrEqualTo(String value) {
            addCriterion("is_delete <=", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteLike(String value) {
            addCriterion("is_delete like", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotLike(String value) {
            addCriterion("is_delete not like", value, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteIn(List<String> values) {
            addCriterion("is_delete in", values, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotIn(List<String> values) {
            addCriterion("is_delete not in", values, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteBetween(String value1, String value2) {
            addCriterion("is_delete between", value1, value2, "is_delete");
            return (Criteria) this;
        }

        public Criteria andIs_deleteNotBetween(String value1, String value2) {
            addCriterion("is_delete not between", value1, value2, "is_delete");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidIsNull() {
            addCriterion("ent_cid is null");
            return (Criteria) this;
        }

        public Criteria andEnt_cidIsNotNull() {
            addCriterion("ent_cid is not null");
            return (Criteria) this;
        }

        public Criteria andEnt_cidEqualTo(Integer value) {
            addCriterion("ent_cid =", value, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidNotEqualTo(Integer value) {
            addCriterion("ent_cid <>", value, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidGreaterThan(Integer value) {
            addCriterion("ent_cid >", value, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ent_cid >=", value, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidLessThan(Integer value) {
            addCriterion("ent_cid <", value, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidLessThanOrEqualTo(Integer value) {
            addCriterion("ent_cid <=", value, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidIn(List<Integer> values) {
            addCriterion("ent_cid in", values, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidNotIn(List<Integer> values) {
            addCriterion("ent_cid not in", values, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidBetween(Integer value1, Integer value2) {
            addCriterion("ent_cid between", value1, value2, "ent_cid");
            return (Criteria) this;
        }

        public Criteria andEnt_cidNotBetween(Integer value1, Integer value2) {
            addCriterion("ent_cid not between", value1, value2, "ent_cid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_ent_product
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 16 11:16:48 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}