package com.gx.model;

import java.math.BigDecimal;
import java.util.Date;

public class ObjEntProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.title
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.m_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private BigDecimal m_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.o_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private BigDecimal o_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer ship_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.min_order
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer min_order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.brand
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.p_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String p_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.after_sale
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String after_sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.invoice
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String invoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.stock
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.stock_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer stock_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.stock_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private BigDecimal stock_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.lower_warn
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer lower_warn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.img_0
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String img_0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.img_1
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String img_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.img_2
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String img_2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.img_3
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String img_3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.img_4
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String img_4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.detail
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.stock_update
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String stock_update;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.period
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.publish
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String publish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.publish_tm
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Date publish_tm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.sale_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer sale_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.is_delete
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String is_delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.cid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_product.ent_cid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer ent_cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.id
     *
     * @return the value of obj_ent_product.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.id
     *
     * @param id the value for obj_ent_product.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.eid
     *
     * @return the value of obj_ent_product.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.eid
     *
     * @param eid the value for obj_ent_product.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEid(Long eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.title
     *
     * @return the value of obj_ent_product.title
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.title
     *
     * @param title the value for obj_ent_product.title
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.m_price
     *
     * @return the value of obj_ent_product.m_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public BigDecimal getM_price() {
        return m_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.m_price
     *
     * @param m_price the value for obj_ent_product.m_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setM_price(BigDecimal m_price) {
        this.m_price = m_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.o_price
     *
     * @return the value of obj_ent_product.o_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public BigDecimal getO_price() {
        return o_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.o_price
     *
     * @param o_price the value for obj_ent_product.o_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setO_price(BigDecimal o_price) {
        this.o_price = o_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.ship_address
     *
     * @return the value of obj_ent_product.ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getShip_address() {
        return ship_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.ship_address
     *
     * @param ship_address the value for obj_ent_product.ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setShip_address(Integer ship_address) {
        this.ship_address = ship_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.min_order
     *
     * @return the value of obj_ent_product.min_order
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getMin_order() {
        return min_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.min_order
     *
     * @param min_order the value for obj_ent_product.min_order
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setMin_order(Integer min_order) {
        this.min_order = min_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.brand
     *
     * @return the value of obj_ent_product.brand
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.brand
     *
     * @param brand the value for obj_ent_product.brand
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.p_type
     *
     * @return the value of obj_ent_product.p_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getP_type() {
        return p_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.p_type
     *
     * @param p_type the value for obj_ent_product.p_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setP_type(String p_type) {
        this.p_type = p_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.after_sale
     *
     * @return the value of obj_ent_product.after_sale
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getAfter_sale() {
        return after_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.after_sale
     *
     * @param after_sale the value for obj_ent_product.after_sale
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setAfter_sale(String after_sale) {
        this.after_sale = after_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.invoice
     *
     * @return the value of obj_ent_product.invoice
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.invoice
     *
     * @param invoice the value for obj_ent_product.invoice
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.stock
     *
     * @return the value of obj_ent_product.stock
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.stock
     *
     * @param stock the value for obj_ent_product.stock
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setStock(String stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.stock_num
     *
     * @return the value of obj_ent_product.stock_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getStock_num() {
        return stock_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.stock_num
     *
     * @param stock_num the value for obj_ent_product.stock_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setStock_num(Integer stock_num) {
        this.stock_num = stock_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.stock_price
     *
     * @return the value of obj_ent_product.stock_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public BigDecimal getStock_price() {
        return stock_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.stock_price
     *
     * @param stock_price the value for obj_ent_product.stock_price
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setStock_price(BigDecimal stock_price) {
        this.stock_price = stock_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.lower_warn
     *
     * @return the value of obj_ent_product.lower_warn
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getLower_warn() {
        return lower_warn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.lower_warn
     *
     * @param lower_warn the value for obj_ent_product.lower_warn
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setLower_warn(Integer lower_warn) {
        this.lower_warn = lower_warn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.img_0
     *
     * @return the value of obj_ent_product.img_0
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getImg_0() {
        return img_0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.img_0
     *
     * @param img_0 the value for obj_ent_product.img_0
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setImg_0(String img_0) {
        this.img_0 = img_0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.img_1
     *
     * @return the value of obj_ent_product.img_1
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getImg_1() {
        return img_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.img_1
     *
     * @param img_1 the value for obj_ent_product.img_1
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setImg_1(String img_1) {
        this.img_1 = img_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.img_2
     *
     * @return the value of obj_ent_product.img_2
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getImg_2() {
        return img_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.img_2
     *
     * @param img_2 the value for obj_ent_product.img_2
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setImg_2(String img_2) {
        this.img_2 = img_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.img_3
     *
     * @return the value of obj_ent_product.img_3
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getImg_3() {
        return img_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.img_3
     *
     * @param img_3 the value for obj_ent_product.img_3
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setImg_3(String img_3) {
        this.img_3 = img_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.img_4
     *
     * @return the value of obj_ent_product.img_4
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getImg_4() {
        return img_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.img_4
     *
     * @param img_4 the value for obj_ent_product.img_4
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setImg_4(String img_4) {
        this.img_4 = img_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.detail
     *
     * @return the value of obj_ent_product.detail
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.detail
     *
     * @param detail the value for obj_ent_product.detail
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.stock_update
     *
     * @return the value of obj_ent_product.stock_update
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getStock_update() {
        return stock_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.stock_update
     *
     * @param stock_update the value for obj_ent_product.stock_update
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setStock_update(String stock_update) {
        this.stock_update = stock_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.period
     *
     * @return the value of obj_ent_product.period
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.period
     *
     * @param period the value for obj_ent_product.period
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.publish
     *
     * @return the value of obj_ent_product.publish
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.publish
     *
     * @param publish the value for obj_ent_product.publish
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPublish(String publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.publish_tm
     *
     * @return the value of obj_ent_product.publish_tm
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Date getPublish_tm() {
        return publish_tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.publish_tm
     *
     * @param publish_tm the value for obj_ent_product.publish_tm
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPublish_tm(Date publish_tm) {
        this.publish_tm = publish_tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.sale_num
     *
     * @return the value of obj_ent_product.sale_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getSale_num() {
        return sale_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.sale_num
     *
     * @param sale_num the value for obj_ent_product.sale_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setSale_num(Integer sale_num) {
        this.sale_num = sale_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.is_delete
     *
     * @return the value of obj_ent_product.is_delete
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.is_delete
     *
     * @param is_delete the value for obj_ent_product.is_delete
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setIs_delete(String is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.cid
     *
     * @return the value of obj_ent_product.cid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.cid
     *
     * @param cid the value for obj_ent_product.cid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_product.ent_cid
     *
     * @return the value of obj_ent_product.ent_cid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getEnt_cid() {
        return ent_cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_product.ent_cid
     *
     * @param ent_cid the value for obj_ent_product.ent_cid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEnt_cid(Integer ent_cid) {
        this.ent_cid = ent_cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", eid=").append(eid);
        sb.append(", title=").append(title);
        sb.append(", m_price=").append(m_price);
        sb.append(", o_price=").append(o_price);
        sb.append(", ship_address=").append(ship_address);
        sb.append(", min_order=").append(min_order);
        sb.append(", brand=").append(brand);
        sb.append(", p_type=").append(p_type);
        sb.append(", after_sale=").append(after_sale);
        sb.append(", invoice=").append(invoice);
        sb.append(", stock=").append(stock);
        sb.append(", stock_num=").append(stock_num);
        sb.append(", stock_price=").append(stock_price);
        sb.append(", lower_warn=").append(lower_warn);
        sb.append(", img_0=").append(img_0);
        sb.append(", img_1=").append(img_1);
        sb.append(", img_2=").append(img_2);
        sb.append(", img_3=").append(img_3);
        sb.append(", img_4=").append(img_4);
        sb.append(", detail=").append(detail);
        sb.append(", stock_update=").append(stock_update);
        sb.append(", period=").append(period);
        sb.append(", publish=").append(publish);
        sb.append(", publish_tm=").append(publish_tm);
        sb.append(", sale_num=").append(sale_num);
        sb.append(", is_delete=").append(is_delete);
        sb.append(", cid=").append(cid);
        sb.append(", ent_cid=").append(ent_cid);
        sb.append("]");
        return sb.toString();
    }
}