package com.gx.model;

public class ObjEntUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_user.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_user.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_user.auth_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String auth_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ent_user.department
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_user.uid
     *
     * @return the value of obj_ent_user.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_user.uid
     *
     * @param uid the value for obj_ent_user.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_user.eid
     *
     * @return the value of obj_ent_user.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_user.eid
     *
     * @param eid the value for obj_ent_user.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEid(Long eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_user.auth_type
     *
     * @return the value of obj_ent_user.auth_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getAuth_type() {
        return auth_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_user.auth_type
     *
     * @param auth_type the value for obj_ent_user.auth_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setAuth_type(String auth_type) {
        this.auth_type = auth_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ent_user.department
     *
     * @return the value of obj_ent_user.department
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ent_user.department
     *
     * @param department the value for obj_ent_user.department
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ent_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", eid=").append(eid);
        sb.append(", auth_type=").append(auth_type);
        sb.append(", department=").append(department);
        sb.append("]");
        return sb.toString();
    }
}