package com.gx.model;

import java.util.Date;

public class ObjIndUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.nick
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.sex
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.real_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String real_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.brithday
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Date brithday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.email
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.company
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.photo
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_ind_user.email_flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String email_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.uid
     *
     * @return the value of obj_ind_user.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.uid
     *
     * @param uid the value for obj_ind_user.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.nick
     *
     * @return the value of obj_ind_user.nick
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.nick
     *
     * @param nick the value for obj_ind_user.nick
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.sex
     *
     * @return the value of obj_ind_user.sex
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.sex
     *
     * @param sex the value for obj_ind_user.sex
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.real_name
     *
     * @return the value of obj_ind_user.real_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getReal_name() {
        return real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.real_name
     *
     * @param real_name the value for obj_ind_user.real_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setReal_name(String real_name) {
        this.real_name = real_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.brithday
     *
     * @return the value of obj_ind_user.brithday
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.brithday
     *
     * @param brithday the value for obj_ind_user.brithday
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.email
     *
     * @return the value of obj_ind_user.email
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.email
     *
     * @param email the value for obj_ind_user.email
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.company
     *
     * @return the value of obj_ind_user.company
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.company
     *
     * @param company the value for obj_ind_user.company
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.photo
     *
     * @return the value of obj_ind_user.photo
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.photo
     *
     * @param photo the value for obj_ind_user.photo
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_ind_user.email_flag
     *
     * @return the value of obj_ind_user.email_flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getEmail_flag() {
        return email_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_ind_user.email_flag
     *
     * @param email_flag the value for obj_ind_user.email_flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEmail_flag(String email_flag) {
        this.email_flag = email_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_ind_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", nick=").append(nick);
        sb.append(", sex=").append(sex);
        sb.append(", real_name=").append(real_name);
        sb.append(", brithday=").append(brithday);
        sb.append(", email=").append(email);
        sb.append(", company=").append(company);
        sb.append(", photo=").append(photo);
        sb.append(", email_flag=").append(email_flag);
        sb.append("]");
        return sb.toString();
    }
}