package com.gx.model;

public class ObjUserShopCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.pid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.buy_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer buy_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.status
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.reject
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String reject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_shop_cart.rejector
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String rejector;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.id
     *
     * @return the value of obj_user_shop_cart.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.id
     *
     * @param id the value for obj_user_shop_cart.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.uid
     *
     * @return the value of obj_user_shop_cart.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.uid
     *
     * @param uid the value for obj_user_shop_cart.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.pid
     *
     * @return the value of obj_user_shop_cart.pid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.pid
     *
     * @param pid the value for obj_user_shop_cart.pid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.buy_num
     *
     * @return the value of obj_user_shop_cart.buy_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getBuy_num() {
        return buy_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.buy_num
     *
     * @param buy_num the value for obj_user_shop_cart.buy_num
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setBuy_num(Integer buy_num) {
        this.buy_num = buy_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.eid
     *
     * @return the value of obj_user_shop_cart.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.eid
     *
     * @param eid the value for obj_user_shop_cart.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEid(Long eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.status
     *
     * @return the value of obj_user_shop_cart.status
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.status
     *
     * @param status the value for obj_user_shop_cart.status
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.reject
     *
     * @return the value of obj_user_shop_cart.reject
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getReject() {
        return reject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.reject
     *
     * @param reject the value for obj_user_shop_cart.reject
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setReject(String reject) {
        this.reject = reject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_shop_cart.rejector
     *
     * @return the value of obj_user_shop_cart.rejector
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getRejector() {
        return rejector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_shop_cart.rejector
     *
     * @param rejector the value for obj_user_shop_cart.rejector
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setRejector(String rejector) {
        this.rejector = rejector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_shop_cart
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", pid=").append(pid);
        sb.append(", buy_num=").append(buy_num);
        sb.append(", eid=").append(eid);
        sb.append(", status=").append(status);
        sb.append(", reject=").append(reject);
        sb.append(", rejector=").append(rejector);
        sb.append("]");
        return sb.toString();
    }
}