package com.gx.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ObjUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public ObjUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andU_typeIsNull() {
            addCriterion("u_type is null");
            return (Criteria) this;
        }

        public Criteria andU_typeIsNotNull() {
            addCriterion("u_type is not null");
            return (Criteria) this;
        }

        public Criteria andU_typeEqualTo(String value) {
            addCriterion("u_type =", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeNotEqualTo(String value) {
            addCriterion("u_type <>", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeGreaterThan(String value) {
            addCriterion("u_type >", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeGreaterThanOrEqualTo(String value) {
            addCriterion("u_type >=", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeLessThan(String value) {
            addCriterion("u_type <", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeLessThanOrEqualTo(String value) {
            addCriterion("u_type <=", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeLike(String value) {
            addCriterion("u_type like", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeNotLike(String value) {
            addCriterion("u_type not like", value, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeIn(List<String> values) {
            addCriterion("u_type in", values, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeNotIn(List<String> values) {
            addCriterion("u_type not in", values, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeBetween(String value1, String value2) {
            addCriterion("u_type between", value1, value2, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_typeNotBetween(String value1, String value2) {
            addCriterion("u_type not between", value1, value2, "u_type");
            return (Criteria) this;
        }

        public Criteria andU_nameIsNull() {
            addCriterion("u_name is null");
            return (Criteria) this;
        }

        public Criteria andU_nameIsNotNull() {
            addCriterion("u_name is not null");
            return (Criteria) this;
        }

        public Criteria andU_nameEqualTo(String value) {
            addCriterion("u_name =", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameNotEqualTo(String value) {
            addCriterion("u_name <>", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameGreaterThan(String value) {
            addCriterion("u_name >", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameGreaterThanOrEqualTo(String value) {
            addCriterion("u_name >=", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameLessThan(String value) {
            addCriterion("u_name <", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameLessThanOrEqualTo(String value) {
            addCriterion("u_name <=", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameLike(String value) {
            addCriterion("u_name like", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameNotLike(String value) {
            addCriterion("u_name not like", value, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameIn(List<String> values) {
            addCriterion("u_name in", values, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameNotIn(List<String> values) {
            addCriterion("u_name not in", values, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameBetween(String value1, String value2) {
            addCriterion("u_name between", value1, value2, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_nameNotBetween(String value1, String value2) {
            addCriterion("u_name not between", value1, value2, "u_name");
            return (Criteria) this;
        }

        public Criteria andU_passIsNull() {
            addCriterion("u_pass is null");
            return (Criteria) this;
        }

        public Criteria andU_passIsNotNull() {
            addCriterion("u_pass is not null");
            return (Criteria) this;
        }

        public Criteria andU_passEqualTo(String value) {
            addCriterion("u_pass =", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passNotEqualTo(String value) {
            addCriterion("u_pass <>", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passGreaterThan(String value) {
            addCriterion("u_pass >", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passGreaterThanOrEqualTo(String value) {
            addCriterion("u_pass >=", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passLessThan(String value) {
            addCriterion("u_pass <", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passLessThanOrEqualTo(String value) {
            addCriterion("u_pass <=", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passLike(String value) {
            addCriterion("u_pass like", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passNotLike(String value) {
            addCriterion("u_pass not like", value, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passIn(List<String> values) {
            addCriterion("u_pass in", values, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passNotIn(List<String> values) {
            addCriterion("u_pass not in", values, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passBetween(String value1, String value2) {
            addCriterion("u_pass between", value1, value2, "u_pass");
            return (Criteria) this;
        }

        public Criteria andU_passNotBetween(String value1, String value2) {
            addCriterion("u_pass not between", value1, value2, "u_pass");
            return (Criteria) this;
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Long value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Long value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Long value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Long value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Long value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Long value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Long> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Long> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Long value1, Long value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Long value1, Long value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andCreate_tmIsNull() {
            addCriterion("create_tm is null");
            return (Criteria) this;
        }

        public Criteria andCreate_tmIsNotNull() {
            addCriterion("create_tm is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_tmEqualTo(Date value) {
            addCriterion("create_tm =", value, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmNotEqualTo(Date value) {
            addCriterion("create_tm <>", value, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmGreaterThan(Date value) {
            addCriterion("create_tm >", value, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmGreaterThanOrEqualTo(Date value) {
            addCriterion("create_tm >=", value, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmLessThan(Date value) {
            addCriterion("create_tm <", value, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmLessThanOrEqualTo(Date value) {
            addCriterion("create_tm <=", value, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmIn(List<Date> values) {
            addCriterion("create_tm in", values, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmNotIn(List<Date> values) {
            addCriterion("create_tm not in", values, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmBetween(Date value1, Date value2) {
            addCriterion("create_tm between", value1, value2, "create_tm");
            return (Criteria) this;
        }

        public Criteria andCreate_tmNotBetween(Date value1, Date value2) {
            addCriterion("create_tm not between", value1, value2, "create_tm");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(String value) {
            addCriterion("isdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(String value) {
            addCriterion("isdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(String value) {
            addCriterion("isdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(String value) {
            addCriterion("isdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(String value) {
            addCriterion("isdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(String value) {
            addCriterion("isdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLike(String value) {
            addCriterion("isdelete like", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotLike(String value) {
            addCriterion("isdelete not like", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<String> values) {
            addCriterion("isdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<String> values) {
            addCriterion("isdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(String value1, String value2) {
            addCriterion("isdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(String value1, String value2) {
            addCriterion("isdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_user
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 16 11:16:48 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}