package com.gx.model;

public class ObjUserShipAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.consignee
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.areaid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.mobile
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.telephone
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.zipcode
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_ship_address.flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Byte flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.id
     *
     * @return the value of obj_user_ship_address.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.id
     *
     * @param id the value for obj_user_ship_address.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.uid
     *
     * @return the value of obj_user_ship_address.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.uid
     *
     * @param uid the value for obj_user_ship_address.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.consignee
     *
     * @return the value of obj_user_ship_address.consignee
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.consignee
     *
     * @param consignee the value for obj_user_ship_address.consignee
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.areaid
     *
     * @return the value of obj_user_ship_address.areaid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.areaid
     *
     * @param areaid the value for obj_user_ship_address.areaid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.address
     *
     * @return the value of obj_user_ship_address.address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.address
     *
     * @param address the value for obj_user_ship_address.address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.mobile
     *
     * @return the value of obj_user_ship_address.mobile
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.mobile
     *
     * @param mobile the value for obj_user_ship_address.mobile
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.telephone
     *
     * @return the value of obj_user_ship_address.telephone
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.telephone
     *
     * @param telephone the value for obj_user_ship_address.telephone
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.zipcode
     *
     * @return the value of obj_user_ship_address.zipcode
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.zipcode
     *
     * @param zipcode the value for obj_user_ship_address.zipcode
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_ship_address.flag
     *
     * @return the value of obj_user_ship_address.flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_ship_address.flag
     *
     * @param flag the value for obj_user_ship_address.flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", consignee=").append(consignee);
        sb.append(", areaid=").append(areaid);
        sb.append(", address=").append(address);
        sb.append(", mobile=").append(mobile);
        sb.append(", telephone=").append(telephone);
        sb.append(", zipcode=").append(zipcode);
        sb.append(", flag=").append(flag);
        sb.append("]");
        return sb.toString();
    }
}