package com.gx.model;

public class ObjUserInvoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.i_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String i_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.title
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Byte flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.company
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.telephone
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.taxpayer
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String taxpayer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.bank
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_invoice.bank_no
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String bank_no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.id
     *
     * @return the value of obj_user_invoice.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.id
     *
     * @param id the value for obj_user_invoice.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.uid
     *
     * @return the value of obj_user_invoice.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.uid
     *
     * @param uid the value for obj_user_invoice.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.i_type
     *
     * @return the value of obj_user_invoice.i_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getI_type() {
        return i_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.i_type
     *
     * @param i_type the value for obj_user_invoice.i_type
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setI_type(String i_type) {
        this.i_type = i_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.title
     *
     * @return the value of obj_user_invoice.title
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.title
     *
     * @param title the value for obj_user_invoice.title
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.flag
     *
     * @return the value of obj_user_invoice.flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.flag
     *
     * @param flag the value for obj_user_invoice.flag
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.company
     *
     * @return the value of obj_user_invoice.company
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.company
     *
     * @param company the value for obj_user_invoice.company
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.telephone
     *
     * @return the value of obj_user_invoice.telephone
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.telephone
     *
     * @param telephone the value for obj_user_invoice.telephone
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.taxpayer
     *
     * @return the value of obj_user_invoice.taxpayer
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getTaxpayer() {
        return taxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.taxpayer
     *
     * @param taxpayer the value for obj_user_invoice.taxpayer
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setTaxpayer(String taxpayer) {
        this.taxpayer = taxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.address
     *
     * @return the value of obj_user_invoice.address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.address
     *
     * @param address the value for obj_user_invoice.address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.bank
     *
     * @return the value of obj_user_invoice.bank
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.bank
     *
     * @param bank the value for obj_user_invoice.bank
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_invoice.bank_no
     *
     * @return the value of obj_user_invoice.bank_no
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getBank_no() {
        return bank_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_invoice.bank_no
     *
     * @param bank_no the value for obj_user_invoice.bank_no
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setBank_no(String bank_no) {
        this.bank_no = bank_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_invoice
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", i_type=").append(i_type);
        sb.append(", title=").append(title);
        sb.append(", flag=").append(flag);
        sb.append(", company=").append(company);
        sb.append(", telephone=").append(telephone);
        sb.append(", taxpayer=").append(taxpayer);
        sb.append(", address=").append(address);
        sb.append(", bank=").append(bank);
        sb.append(", bank_no=").append(bank_no);
        sb.append("]");
        return sb.toString();
    }
}