package com.gx.model;

public class ObjUserCollectProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_collect_product.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_collect_product.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_collect_product.pid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_collect_product.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Long eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column obj_user_collect_product.remarks
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_collect_product.id
     *
     * @return the value of obj_user_collect_product.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_collect_product.id
     *
     * @param id the value for obj_user_collect_product.id
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_collect_product.uid
     *
     * @return the value of obj_user_collect_product.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_collect_product.uid
     *
     * @param uid the value for obj_user_collect_product.uid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_collect_product.pid
     *
     * @return the value of obj_user_collect_product.pid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_collect_product.pid
     *
     * @param pid the value for obj_user_collect_product.pid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_collect_product.eid
     *
     * @return the value of obj_user_collect_product.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Long getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_collect_product.eid
     *
     * @param eid the value for obj_user_collect_product.eid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEid(Long eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column obj_user_collect_product.remarks
     *
     * @return the value of obj_user_collect_product.remarks
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column obj_user_collect_product.remarks
     *
     * @param remarks the value for obj_user_collect_product.remarks
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_product
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", uid=").append(uid);
        sb.append(", pid=").append(pid);
        sb.append(", eid=").append(eid);
        sb.append(", remarks=").append(remarks);
        sb.append("]");
        return sb.toString();
    }
}