package com.gx.model;

public class RefArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.areaid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.by_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String by_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.fatherid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer fatherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.path_level
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Byte path_level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.first_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String first_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.english_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String english_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_area.is_delete
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private String is_delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.areaid
     *
     * @return the value of ref_area.areaid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.areaid
     *
     * @param areaid the value for ref_area.areaid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.name
     *
     * @return the value of ref_area.name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.name
     *
     * @param name the value for ref_area.name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.by_name
     *
     * @return the value of ref_area.by_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getBy_name() {
        return by_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.by_name
     *
     * @param by_name the value for ref_area.by_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setBy_name(String by_name) {
        this.by_name = by_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.fatherid
     *
     * @return the value of ref_area.fatherid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.fatherid
     *
     * @param fatherid the value for ref_area.fatherid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.path_level
     *
     * @return the value of ref_area.path_level
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Byte getPath_level() {
        return path_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.path_level
     *
     * @param path_level the value for ref_area.path_level
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setPath_level(Byte path_level) {
        this.path_level = path_level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.first_name
     *
     * @return the value of ref_area.first_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getFirst_name() {
        return first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.first_name
     *
     * @param first_name the value for ref_area.first_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.english_name
     *
     * @return the value of ref_area.english_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getEnglish_name() {
        return english_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.english_name
     *
     * @param english_name the value for ref_area.english_name
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setEnglish_name(String english_name) {
        this.english_name = english_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_area.is_delete
     *
     * @return the value of ref_area.is_delete
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public String getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_area.is_delete
     *
     * @param is_delete the value for ref_area.is_delete
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setIs_delete(String is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_area
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", areaid=").append(areaid);
        sb.append(", name=").append(name);
        sb.append(", by_name=").append(by_name);
        sb.append(", fatherid=").append(fatherid);
        sb.append(", path_level=").append(path_level);
        sb.append(", first_name=").append(first_name);
        sb.append(", english_name=").append(english_name);
        sb.append(", is_delete=").append(is_delete);
        sb.append("]");
        return sb.toString();
    }
}