package com.gx.model;

public class RefIndustry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_industry.industryid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    private Integer industryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_industry.industryid
     *
     * @return the value of ref_industry.industryid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public Integer getIndustryid() {
        return industryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_industry.industryid
     *
     * @param industryid the value for ref_industry.industryid
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    public void setIndustryid(Integer industryid) {
        this.industryid = industryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", industryid=").append(industryid);
        sb.append("]");
        return sb.toString();
    }
}