package com.stark.app.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PASSWORD
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DESCRIPTION
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.STATE
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.by_name
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    private String byName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DESCRIPTION
     *
     * @return the value of user.DESCRIPTION
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DESCRIPTION
     *
     * @param description the value for user.DESCRIPTION
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.STATE
     *
     * @return the value of user.STATE
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.STATE
     *
     * @param state the value for user.STATE
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.by_name
     *
     * @return the value of user.by_name
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public String getByName() {
        return byName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.by_name
     *
     * @param byName the value for user.by_name
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    public void setByName(String byName) {
        this.byName = byName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Aug 31 17:35:03 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", description=").append(description);
        sb.append(", state=").append(state);
        sb.append(", byName=").append(byName);
        sb.append("]");
        return sb.toString();
    }
}