package com.gx.dao;

import com.gx.model.ObjProductEvaluation;
import com.gx.model.ObjProductEvaluationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObjProductEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int countByExample(ObjProductEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByExample(ObjProductEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insert(ObjProductEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insertSelective(ObjProductEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    List<ObjProductEvaluation> selectByExample(ObjProductEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    ObjProductEvaluation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") ObjProductEvaluation record, @Param("example") ObjProductEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExample(@Param("record") ObjProductEvaluation record, @Param("example") ObjProductEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKeySelective(ObjProductEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_product_evaluation
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKey(ObjProductEvaluation record);
}