package com.gx.dao;

import com.gx.model.ObjUser;
import com.gx.model.ObjUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObjUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int countByExample(ObjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByExample(ObjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insert(ObjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insertSelective(ObjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    List<ObjUser> selectByExample(ObjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    ObjUser selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") ObjUser record, @Param("example") ObjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExample(@Param("record") ObjUser record, @Param("example") ObjUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKeySelective(ObjUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKey(ObjUser record);
}