package com.gx.dao;

import com.gx.model.ObjUserCollectEnt;
import com.gx.model.ObjUserCollectEntExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObjUserCollectEntMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int countByExample(ObjUserCollectEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByExample(ObjUserCollectEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insert(ObjUserCollectEnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insertSelective(ObjUserCollectEnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    List<ObjUserCollectEnt> selectByExample(ObjUserCollectEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    ObjUserCollectEnt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") ObjUserCollectEnt record, @Param("example") ObjUserCollectEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExample(@Param("record") ObjUserCollectEnt record, @Param("example") ObjUserCollectEntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKeySelective(ObjUserCollectEnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_collect_ent
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKey(ObjUserCollectEnt record);
}