package com.gx.dao;

import com.gx.model.ObjUserShipAddress;
import com.gx.model.ObjUserShipAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ObjUserShipAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int countByExample(ObjUserShipAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByExample(ObjUserShipAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insert(ObjUserShipAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insertSelective(ObjUserShipAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    List<ObjUserShipAddress> selectByExample(ObjUserShipAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    ObjUserShipAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") ObjUserShipAddress record, @Param("example") ObjUserShipAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExample(@Param("record") ObjUserShipAddress record, @Param("example") ObjUserShipAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKeySelective(ObjUserShipAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table obj_user_ship_address
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByPrimaryKey(ObjUserShipAddress record);
}