package com.gx.dao;

import com.gx.model.RefIndustry;
import com.gx.model.RefIndustryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int countByExample(RefIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByExample(RefIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int deleteByPrimaryKey(Integer industryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insert(RefIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int insertSelective(RefIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    List<RefIndustry> selectByExample(RefIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExampleSelective(@Param("record") RefIndustry record, @Param("example") RefIndustryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_industry
     *
     * @mbggenerated Fri Sep 16 11:16:48 CST 2016
     */
    int updateByExample(@Param("record") RefIndustry record, @Param("example") RefIndustryExample example);
}